### ISSUE TITLE
website rendering a white page

### ISSUE THREAD

**Issue by ghostsquad** [nfriend/tree-online#2]
Your website appears to just be render a white/empty page.

**Comment by nfriend** [comment]
@ghostsquad Thanks so much for drawing my attention to this! Will investigate 🔍

**Comment by nfriend** [comment]
Fixed in https://github.com/nfriend/tree-online/commit/a29c148165a38cc67c30dd31c2fc6b6cc70e226a 🙂 

Thanks again for the report @ghostsquad!
