### ISSUE TITLE
Is it possible to generate a tree automatically when provided with a link?

### ISSUE THREAD

**Issue by seanswyi** [nfriend/tree-online#23]
I'm not sure if this is possible as I'm not familiar with web technology, but would it be possible to create something like providing the URL to a GitHub repository, then automatically generating a file-like structure from that?

**Comment by nfriend-stripe** [comment]
Hi @seanswyi - This would be a bit tricky as it would would require either cloning the Git repository to navigate its structure or scraping GitHub's interface to get the underlying file structure. In either case, this would probably make more sense to do server-side, and at the moment this web app is a purely frontend application.

Thanks for the suggestion, though!

**Comment by nfriend** [comment]
Hi @seanswyi - This would be a bit tricky as it would would require either cloning the Git repository to navigate its structure or scraping GitHub's interface to get the underlying file structure. In either case, this would probably make more sense to do server-side, and at the moment this web app is a purely frontend application.

Thanks for the suggestion, though!
